
export const INITIAL_STATS = {
  health: 100,
  hunger: 100,
  thirst: 100,
  energy: 100,
  temperature: 20,
};

export const SURVIVAL_DECAY_RATES = {
  hunger: 0.12,         // ~14 mins from 100 to 0
  thirst: 0.18,         // ~9 mins from 100 to 0
  energy_base: 0.02,     // Constant drain
  energy_walk: 0.15,     // Drain while walking
  energy_sprint: 0.45,   // Drain while sprinting
  energy_recovery: 0.4,  // Recovery when standing still
  energy_fire_gain: 0.6, // Extra recovery when near fire
  temp_night_drop: 0.25, // Temperature drop per sec at night
  temp_day_drop: 0.08,   // Temperature drop per sec at day
  temp_fire_gain: 0.8,   // Temperature gain near fire
};

export const COLORS = {
  health: '#ef4444',
  hunger: '#f59e0b',
  thirst: '#3b82f6',
  energy: '#10b981',
  temperature: '#f43f5e',
};

export const TRANSLATIONS = {
  en: {
    newGame: "NEW GAME",
    continue: "CONTINUE",
    settings: "SETTINGS",
    saveLoaded: "SAVE LOADED",
    resetProgress: "RESET PROGRESS",
    youDied: "YOU DIED",
    wildernessReclaimed: "The wilderness has reclaimed another soul.",
    tryAgain: "TRY AGAIN",
    day: "DAY",
    health: "HEALTH",
    hunger: "HUNGER",
    thirst: "THIRST",
    energy: "ENERGY",
    temp: "TEMP",
    emptyInventory: "Inventory is empty...",
    use: "USE",
    tree: "CHOP TREE",
    appleTree: "GATHER APPLES",
    bush: "PICK BERRIES",
    rock: "COLLECT STONE",
    water: "DRINK WATER",
    campfire: "COOK FOOD / WARM UP",
    critter: "HUNT ANIMAL",
    rabbit: "HUNT RABBIT",
    partridge: "HUNT PARTRIDGE",
    arrow: "PICK UP ARROW",
    walk: "WALK",
    look: "LOOK",
    action: "ACTION",
    pause: "PAUSE",
    music: "MUSIC",
    sfx: "SFX",
    language: "LANGUAGE",
    close: "CLOSE",
    back: "BACK TO MENU",
    interact: "INTERACT (E / CLICK)",
    craft: "CRAFT CAMPFIRE (C)",
    notEnough: "NEED 1 FLINT, 3 WOOD",
    craftArrow: "CRAFT ARROWS (X)",
    notEnoughWood: "NEED 1 WOOD",
    craftBow: "CRAFT BOW (V)",
    notEnoughBowWood: "NEED 3 WOOD",
    craftTorch: "CRAFT TORCH (T)",
    notEnoughTorch: "NEED 1 WOOD, 1 FLINT",
    roastedApple: "ROASTED APPLE",
    cookedBerries: "COOKED BERRIES",
    rawMeat: "RAW MEAT",
    cookedMeat: "COOKED MEAT",
    Arrow: "ARROW",
    Bow: "BOW",
    Torch: "TORCH",
    todoList: "TO-DO LIST",
    taskWood: "Gather Wood",
    taskFlint: "Find Flint Stone",
    taskCampfire: "Build a Campfire",
    taskBow: "Craft a Bow",
    taskTorch: "Craft a Torch",
    taskMeat: "Hunt for Meat",
    tagline: "Survive in the Wildlands",
    on: "ON",
    off: "OFF",
    waterDetail: "Clean mountain water. Restores 20% Thirst.",
    appleTreeDetail: "High-energy wild apples. Best for hunger.",
    bushDetail: "Wild berries. Good for quick energy bursts.",
    treeDetail: "Provides wood for building and heat.",
    rockDetail: "Solid stone. Used for crafting flint and arrows.",
    campfireDetail: "Restores body temperature and allows cooking.",
    arrowDetail: "A projectile that can be retrieved and reused."
  },
  tr: {
    newGame: "YENİ OYUN",
    continue: "DEVAM ET",
    settings: "AYARLAR",
    saveLoaded: "KAYIT YÜKLENDİ",
    resetProgress: "İLERLEMEYİ SIFIRLA",
    youDied: "ÖLDÜNÜZ",
    wildernessReclaimed: "Vahşi doğa sizi yuttu.",
    tryAgain: "YENİDEN BAŞLA",
    day: "GÜN",
    health: "SAĞLIK",
    hunger: "AÇLIK",
    thirst: "SUSUZLUK",
    energy: "ENERJİ",
    temp: "SICAKLIK",
    emptyInventory: "Envanter boş...",
    use: "KULLAN",
    tree: "AĞAÇ KES",
    appleTree: "ELMA TOPLA",
    bush: "BÖĞÜRTLEN TOPLA",
    rock: "TAŞ TOPLA",
    water: "SU İÇ",
    campfire: "YEMEK PİŞİR / ISIN",
    critter: "HAYVAN AVLA",
    rabbit: "TAVŞAN AVLA",
    partridge: "KEKLİK AVLA",
    arrow: "OKU TOPLA",
    walk: "YÜRÜ",
    look: "BAKIŞ",
    action: "ETKİLEŞİM (E / TIKLA)",
    pause: "DURDUR",
    music: "MÜZİK",
    sfx: "SES EFEKTİ",
    language: "DİL",
    close: "KAPAT",
    back: "MENÜYE DÖN",
    interact: "ETKİLEŞİME GEÇ",
    craft: "ATEŞ YAK (C)",
    notEnough: "1 ÇAKMAKTAŞI, 3 ODUN GEREKLİ",
    craftArrow: "OK YAP (X)",
    notEnoughWood: "1 ODUN GEREKLİ",
    craftBow: "YAY YAP (V)",
    notEnoughBowWood: "3 ODUN GEREKLİ",
    craftTorch: "MEŞALE YAP (T)",
    notEnoughTorch: "1 ODUN, 1 ÇAKMAKTAŞI GEREKLİ",
    roastedApple: "KIZARMIŞ ELMA",
    cookedBerries: "PİŞMİŞ BÖĞÜRTLEN",
    rawMeat: "ÇİĞ ET",
    cookedMeat: "PİŞMİŞ ET",
    Arrow: "OK",
    Bow: "YAY",
    Torch: "MEŞALE",
    todoList: "YAPILACAKLAR",
    taskWood: "Odun Topla",
    taskFlint: "Çakmaktaşı Bul",
    taskCampfire: "Kamp Ateşi Yak",
    taskBow: "Yay Üret",
    taskTorch: "Meşale Yap",
    taskMeat: "Avlan ve Et Bul",
    tagline: "Vahşi Doğada Hayatta Kal",
    on: "AÇIK",
    off: "KAPALI",
    waterDetail: "Temiz dağ suyu. %20 Susuzluk giderir.",
    appleTreeDetail: "Yabani elmalar. Açlık için en iyisidir.",
    bushDetail: "Yabani meyveler. Hızlı enerji için ideal.",
    treeDetail: "Isınma ve üretim için odun sağlar.",
    rockDetail: "Ok ve çakmaktaşı üretimi için ham taş.",
    campfireDetail: "Vücut ısısını dengeler ve yemek pişirir.",
    arrowDetail: "Atılan oku yerden alarak tekrar kullanabilirsin."
  }
};

export const SFX_URLS = {
  hunger_critical: 'https://assets.mixkit.co/sfx/preview/mixkit-stomach-growl-1234.mp3',
  thirst_critical: 'https://assets.mixkit.co/sfx/preview/mixkit-dry-swallow-1323.mp3',
  footstep_grass: 'https://codeskulptor-demos.commondatastorage.googleapis.com/descent/footstep_grass_1.mp3',
  footstep_stone: 'https://codeskulptor-demos.commondatastorage.googleapis.com/descent/footstep_stone_1.mp3',
  footstep_water: 'https://assets.mixkit.co/sfx/preview/mixkit-splashing-in-puddles-2189.mp3',
  bird_ambient: 'https://assets.mixkit.co/sfx/preview/mixkit-forest-birds-singing-background-ambience-1210.mp3',
  squirrel_ambient: 'https://assets.mixkit.co/sfx/preview/mixkit-squirrel-chatter-noise-1211.mp3',
  collect_wood: 'https://assets.mixkit.co/sfx/preview/mixkit-wood-hard-hit-2129.mp3',
  collect_stone: 'https://assets.mixkit.co/sfx/preview/mixkit-stone-hit-heavy-impact-2134.mp3',
  collect_meat: 'https://assets.mixkit.co/sfx/preview/mixkit-sword-impact-on-flesh-2616.mp3',
  collect_item_generic: 'https://assets.mixkit.co/sfx/preview/mixkit-nature-movement-in-the-grass-1215.mp3',
  drink_splash: 'https://assets.mixkit.co/sfx/preview/mixkit-water-splash-1121.mp3',
  drink_swallow: 'https://assets.mixkit.co/sfx/preview/mixkit-drinking-swallow-2244.mp3',
  eat_crunchy: 'https://assets.mixkit.co/sfx/preview/mixkit-eating-crunchy-food-2243.mp3',
  campfire_craft: 'https://assets.mixkit.co/sfx/preview/mixkit-fire-crackling-burning-1333.mp3',
  campfire_cook: 'https://assets.mixkit.co/sfx/preview/mixkit-fire-ignition-flame-1340.mp3',
  arrow_shoot: 'https://assets.mixkit.co/sfx/preview/mixkit-fast-bow-shoot-2633.mp3',
  arrow_impact: 'https://assets.mixkit.co/sfx/preview/mixkit-arrow-impact-on-wood-2169.mp3',
  torch_light: 'https://assets.mixkit.co/sfx/preview/mixkit-fire-flare-1334.mp3',
  rain_ambient: 'https://assets.mixkit.co/sfx/preview/mixkit-light-rain-loop-2393.mp3',
  ui_click: 'https://assets.mixkit.co/sfx/preview/mixkit-modern-click-box-check-1120.mp3',
  ui_hover: 'https://assets.mixkit.co/sfx/preview/mixkit-simple-click-interface-sound-2564.mp3'
};
